### PR TITLE
Track customers interactions with the website (#39)

### LINKED ISSUE #39: Track customers' interactions with the website
Active Campaign allows to track customers' interactions with the website, in particular visited pages.

Documentation:
https://help.activecampaign.com/hc/it/articles/221542267-Una-panoramica-del-monitoraggio-del-sito
https://www.activecampaign.com/learn/guides/a-guide-to-site-tracking

### PR DESCRIPTION
**Pull request by lruozzi9**
Fixes #39 

Changes proposed in this pull request:
- Add tracking scripts to website

@webgriffe/wg-devs what do you think about this PR :shipit:?

### CODE REVIEW

**Comment by minimit** [comment]
One more tracker. why?

**Review by LucaGallinari — APPROVED** [review]
For me it's ok.
We could get the customer directly from the global variable "sylius" by using "sylius.customer" in the template. But i don't really like global variables 😅,  so for me it's good as you proposed.

**Comment by LucaGallinari** [comment]
@minimit It's explained in the issue: https://github.com/webgriffe/SyliusActiveCampaignPlugin/issues/39

**Comment by lruozzi9** [comment]
> For me it's ok. We could get the customer directly from the global variable "sylius" by using "sylius.customer" in the template. But i don't really like global variables 😅, so for me it's good as you proposed.

I agree and it is also for sure more customizable for users!

**Pull request merged**
